(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["events_$slug"],{

/***/ "./src/routes/events/[slug].svelte":
/*!*****************************************!*\
  !*** ./src/routes/events/[slug].svelte ***!
  \*****************************************/
/*! exports provided: default, preload */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "preload", function() { return preload; });
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/routes/events/[slug].svelte generated by Svelte v3.21.0 */


const { console: console_1 } = svelte_internal__WEBPACK_IMPORTED_MODULE_0__["globals"];
const file = "src/routes/events/[slug].svelte";

function create_fragment(ctx) {
	let h1;
	let t_value = /*event*/ ctx[0].slug + "";
	let t;

	const block = {
		c: function create() {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])(t_value);
			this.h();
		},
		l: function claim(nodes) {
			h1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "H1", {});
			var h1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h1);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h1_nodes, t_value);
			h1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h1, file, 21, 0, 230);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, h1, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h1, t);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*event*/ 1 && t_value !== (t_value = /*event*/ ctx[0].slug + "")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["set_data_dev"])(t, t_value);
		},
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(h1);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

async function preload(page, session) {
	const { slug } = page.params;
	return { event: { slug } };
}

function instance($$self, $$props, $$invalidate) {
	let { event } = $$props;
	const writable_props = ["event"];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console_1.warn(`<U5Bslugu5D> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("U5Bslugu5D", $$slots, []);

	$$self.$set = $$props => {
		if ("event" in $$props) $$invalidate(0, event = $$props.event);
	};

	$$self.$capture_state = () => ({ preload, event });

	$$self.$inject_state = $$props => {
		if ("event" in $$props) $$invalidate(0, event = $$props.event);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*event*/ 1) {
			$: console.log(event);
		}
	};

	return [event];
}

class U5Bslugu5D extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], { event: 0 });

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "U5Bslugu5D",
			options,
			id: create_fragment.name
		});

		const { ctx } = this.$$;
		const props = options.props || {};

		if (/*event*/ ctx[0] === undefined && !("event" in props)) {
			console_1.warn("<U5Bslugu5D> was created without expected prop 'event'");
		}
	}

	get event() {
		throw new Error("<U5Bslugu5D>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set event(value) {
		throw new Error("<U5Bslugu5D>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

/* harmony default export */ __webpack_exports__["default"] = (U5Bslugu5D);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvcm91dGVzL2V2ZW50cy9bc2x1Z10uc3ZlbHRlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozt5QkFzQk0sR0FBSyxJQUFDLElBQUk7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsrREFBVixHQUFLLElBQUMsSUFBSTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7ZUFwQk8sT0FBTyxDQUFDLElBQUksRUFBRSxPQUFPO1NBRWxDLElBQUksS0FBSyxJQUFJLENBQUMsTUFBTTtVQUduQixLQUFLLElBQUksSUFBSTs7OztPQUxULEtBQUs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0dBRWhCLENBQUMsRUFBRSxPQUFPLENBQUMsR0FBRyxDQUFFLEtBQUsiLCJmaWxlIjoiMjUxZTBlNWRjOGM5OTA5M2QzMGIvZXZlbnRzXyRzbHVnLmV2ZW50c18kc2x1Zy5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQgY29udGV4dD1cIm1vZHVsZVwiPlxuXG5cdGV4cG9ydCBhc3luYyBmdW5jdGlvbiBwcmVsb2FkKHBhZ2UsIHNlc3Npb24pIHtcblxuXHRcdGNvbnN0IHsgc2x1ZyB9ID0gcGFnZS5wYXJhbXM7XG5cblxuXHRcdHJldHVybiB7IGV2ZW50OiB7IHNsdWcgfSB9O1xuXHR9XG48L3NjcmlwdD5cblxuPHNjcmlwdD5cblx0XG4gICAgZXhwb3J0IGxldCBldmVudDtcblxuICAgICQ6IGNvbnNvbGUubG9nKCBldmVudCApXG5cbjwvc2NyaXB0PlxuXG5cblxuPGgxPlxuICAgIHsgZXZlbnQuc2x1ZyB9XG48L2gxPiJdLCJzb3VyY2VSb290IjoiIn0=